trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

- script: |
    python --version
    python -m pip install --upgrade pip
    pip install dbt-snowflake
    dbt --version
  displayName: 'Install dbt'

- script: |
    cd travel360_dbt
    echo "Travel360 dbt project"
    ls -la
  displayName: 'Check dbt Project'