pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('DBT Debug') {
            steps {
                bat 'D:\\Travel360\\Project\\travel360dbt\\.venv\\Scripts\\dbt.exe debug --project-dir travel360_dbt'
            }
        }

        stage('DBT Run') {
            steps {
                bat 'D:\\Travel360\\Project\\travel360dbt\\.venv\\Scripts\\dbt.exe run --project-dir travel360_dbt'
            }
        }

        stage('DBT Test') {
            steps {
                bat 'D:\\Travel360\\Project\\travel360dbt\\.venv\\Scripts\\dbt.exe test --project-dir travel360_dbt'
            }
        }
    }
}